config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create] do
    resources :my_classes, shallow: true
  end
  resources :my_classes, only: [:show, :index, :edit] do
    resources :students, shallow: true
  end
  get 'home', to: 'pages#home'
  get 'random_student', to: 'pages#random_student'
  get 'random_group', to: 'pages#random_group'
  post 'my_students', to: 'my_classes#my_students'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'
  get 'authorized', to: 'sessions#page_requires_login'

  root 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_class.rb
class MyClass < ApplicationRecord
  belongs_to :user
  has_many :students
  validates :class_name, presence: true, uniqueness: { scope: :user_id }
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :my_class
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :my_classes

    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password_digest, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authorized
helper_method :current_user
helper_method :logged_in?

    def current_user
        User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
    def authorized
        redirect_to '/home' unless logged_in?
    end

end

app/controllers/my_classes_controller.rb
class MyClassesController < ApplicationController

    def index
        user = User.find(session[:user_id])
        @my_classes = user.my_classes.all
    end
    def edit
        my_class = MyClass.find(params[:id])
        @class_id = my_class.id
        @class_name = my_class.class_name
        @students = my_class.students.all
    end
    def new
        @user = User.find(session[:user_id])
    end
    def update
        my_class = MyClass.find(params[:id].to_i)
        params[:data].each do |key, value|
            if value[:id]
                student = Student.find(value[:id])
                student.update({first_name: value[:first_name], last_name: value[:last_name], birthday: value[:birthday]})
            else
                student = my_class.students.create({first_name: value[:first_name], last_name: value[:last_name], birthday: value[:birthday]})
                if student.valid?
                    puts "successfully added new student"
                end
            end
        end
        render json: my_class.to_json(include: [:students])
    end
    def my_students
        puts params
        my_class = MyClass.find(params[:id].to_i)
        render json: my_class.to_json(include: [:students])
    end
    def create
        @user = User.find(session[:user_id])
        my_class = @user.my_classes.create(my_class_params)
        if my_class.valid?
            redirect_to edit_my_class_path(my_class)
        else
            flash[:alert] = 'That class name is already taken.'
            render "new"
        end
    end

    private

    def my_class_params
        params.require(:my_class).permit(:class_name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authorized, only: [:home]
    def home
        @user = current_user
    end
    def random_student
        user = User.find(session[:user_id])
        @my_classes = user.my_classes.all
    end
    def random_group
        user = User.find(session[:user_id])
        @my_classes = user.my_classes.all
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/home'
    else
      redirect_to '/login'
    end
  end

  def logout
    reset_session
    redirect_to '/home'
  end

  def login
  end

  def welcome
  end

  def page_requires_login
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
    
    end
    def create
        @my_class = MyClass.find(params[:my_class_id])
        @student = @my_class.students.create(student_params)
        if @student.valid?
            render :new
        else
            render :new
        end
    end
    def new
        @my_class = MyClass.find(params[:my_class_id])
    end

    def update
        p params
    end
    def destroy
        puts "THIS IS THE DESTROY METHOD HERE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        student = Student.find(params[:id])
        p student
        student.destroy!
        render json: student
    end

    private

    def student_params
        params.require(:student).permit(:first_name, :last_name, :birthday)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :password))
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to '/home'
    else
      render json: @user.errors.messages.to_json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_classes_helper.rb
module MyClassesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Happy+Monkey&family=Nunito&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <div class="nav-menu">
      <a href="/"><%= image_tag 'icon.png', id: "icon"%></a>
      <% if logged_in? %>
      <%= link_to  "Random student generator", '/random_student' %>
      <%= link_to  "Random group maker", '/random_group' %>
      <%= link_to "New class", new_user_my_class_path(session[:user_id]) %>
      <%= link_to "Edit classes", my_classes_path %>
      <%= link_to  "Logout", logout_path %>
      <% else %>
      <%= link_to  "Login", login_path %>
      <%= link_to  "Sign up", new_user_path %>
      <% end %>
    </div>
  <div class="burger">
    <div class="slice"></div>
    <div class="slice"></div>
    <div class="slice"></div>
  </div>
  </nav>
  <%=javascript_pack_tag 'template/template.js'%>
    <%= yield %>
  </body>
</html>

app/views/my_classes/edit.html.erb
<h1>Editing <%=@class_name %>!</h1>

<form>
<table>
    <thead>
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Birthday</th>
        </tr>
    </thead>
    <tbody>
    <%@students.each do |student|%>
        <tr id="<%=student.id%>">
        <td class="td-first_name"><input type="text" name="first_name" id="<%=student.id%>" value="<%= student.first_name %> " required/></td>
        <td class="td-last_name"><input type="text" name="last_name" id="<%=student.id%>" value="<%= student.last_name %> " required/></td>
        <td class="td-birthday"><input type="date" name="birthday" id="<%=student.id%>" value="<%=student.birthday%>"/></td>
        <td class="trash"><%= fa_icon "trash" %></td>
        <tr>
    <% end %>
    </tbody>
</table>
<button type="button" id="add-student-butt" class="btn-red">Add student</button>
<button type="submit" id="save-butt" class="btn-red">Save</button>

</form>


<%= javascript_pack_tag 'my_classes/edit'%>

app/views/my_classes/index.html.erb
<h1>Choose a class to edit<h1>
<ul>
<% @my_classes.each do |my_class| %>
        <li>🌟 <%= link_to  my_class.class_name, edit_my_class_path(my_class) %></li>
<% end %>
</ul>

app/views/my_classes/new.html.erb
<h1>Create a new class</h1>

<%= form_with model: [@user, @user.my_classes.build], local: true do |f| %>
    <%= f.text_field :class_name %>
    <%= f.submit "Save" %>
<% end %>

<% flash.each do |type, msg| %>
    <div>
        <%= msg %>
    </div>
<% end %>

app/views/pages/_class_select.html.erb
<select id="class-select">
<option value="" disabled selected hidden>Select class...</option>
<% @my_classes.each do |my_class| %>
<option value="<%=my_class.id%>" ><%=my_class.class_name%></option>
<%end%>
</select>

app/views/pages/home.html.erb
<div class="hero">
  <div class="main-title">Teacher's Pets</div>
  <h1>Everything you need to manage your classroom in one place</h1>
   <% if logged_in? %>
    <a href ="/my_classes" class="link-btn">Edit classes</a>
   <% else %>
   <a href ="/users/new" class="link-btn">Sign up</a>
   <% end %>
</div>

app/views/pages/random_group.html.erb
<div class="pages-top">
<h1>Random Group Maker</h1>
<div class="select-controls">
<%= render 'class_select' %>
<select id="student-number-select">
<option value="" disabled selected hidden>Minimum students per group</option></select>
<button class="btn-red">Make groups</button>
</div>
</div>

<div id="group-display"></div>

<%= javascript_pack_tag 'pages/random_group'%>

app/views/pages/random_student.html.erb
<div class="pages-top">
<h1>Random student generator</h1>
<div class="select-controls">
<%= render 'class_select'%>

<button class="btn-red">Random Student</button>
</div>

<div id="student-name-display"><span id="student-name-span"></span><span class="b-day-span"></span></div>
</div>

<%=javascript_pack_tag "pages/random_student"%>

app/views/students/new.html.erb
<h1>Add a new student!</h1>
 

<%= form_with model: [@my_class, @my_class.students.build], local: true do |f| %>
    <%= f.text_field :first_name %>
    <br>
    <%= f.text_field :last_name %>
    <br>
    <%= f.date_field :birthday %>
    <br>
    <%= f.submit "Save student"%>
<% end %>

<% @my_class.students.each do |student|%>
<p><%= student[:first_name]%> <%= student[:last_name] %></p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div id="signup-container">
<h1>Sign Up</h1>
<%= form_with( model: @user, id: "signup-form", local: false) do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username, :required => true%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password, :required => true%><br>
  <%= submit_tag "Sign Up", class: 'btn-red'%>
<%end%>
</div>


<% if @user.errors.messages[:username][0]
    @user.errors.messages[:username].each do |message|%>
    <p><%= message %></p>
    <% end %>
<% end %>


<% if @user.errors.messages[:password][0]
    @user.errors.messages[:password].each do |message|%>
    <p><%= message %></p>
    <% end %>
<% end %>

<%= javascript_pack_tag 'users/new' %>